name: Release

on:
  push:
    branches:
      - main

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: pnpm

      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@v2
        with:
          private_key: ${{ secrets.CEX_WORKER_SECRET }}
          app_id: 408712

      - run: pnpm i

      - run: pnpm run build-lib

      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.GH_NPM_TOKEN }}
        run: npx semantic-release
