name: Node.js CI

on:
  push:
    branches:
      - main

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@v2
        with:
          private_key: ${{ secrets.CEX_WORKER_SECRET }}
          app_id: 408712

      - run: pnpm ci

      - run: pnpm run build-lib

      - name: Release
        env:
          GH_NPM_TOKEN: '${{ secrets.GH_NPM_TOKEN }}'
          GITHUB_TOKEN: '${{ steps.get_token.outputs.token }}'
        run: npx semantic-release
